# ---------------------------------------------------------------
# Lookups
# ---------------------------------------------------------------

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

data "aws_vpc" "default" {
  default = true
}

data "http" "my_ip" {
  url = "https://checkip.amazonaws.com"
}

locals {
  ssh_cidr     = var.ssh_cidr != "" ? var.ssh_cidr : "${chomp(data.http.my_ip.response_body)}/32"
  worker_names = ["client1", "client2"] # deploy.sh / inventory expect exactly these two
}

# ---------------------------------------------------------------
# SSH key - generated by Terraform, replaces the manual PEM paste
# ---------------------------------------------------------------

resource "tls_private_key" "cluster" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "cluster" {
  key_name_prefix = "k8s-lab-"
  public_key      = tls_private_key.cluster.public_key_openssh
}

# Local copy so you can SSH in yourself
resource "local_sensitive_file" "private_key" {
  filename        = "${path.module}/k8s-lab.pem"
  content         = tls_private_key.cluster.private_key_openssh
  file_permission = "0400"
}

# ---------------------------------------------------------------
# Security group
# ---------------------------------------------------------------

resource "aws_security_group" "k8s" {
  name_prefix = "k8s-lab-"
  description = "k8s lab cluster"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH from you"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [local.ssh_cidr]
  }

  ingress {
    description = "Kubernetes API from you"
    from_port   = 6443
    to_port     = 6443
    protocol    = "tcp"
    cidr_blocks = [local.ssh_cidr]
  }

  ingress {
    description = "All traffic between cluster nodes (kubelet, etcd, flannel VXLAN, NodePorts)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    self        = true
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------
# Instances
# ---------------------------------------------------------------

resource "aws_instance" "workers" {
  count = length(local.worker_names)

  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.worker_instance_type
  key_name               = aws_key_pair.cluster.key_name
  vpc_security_group_ids = [aws_security_group.k8s.id]

  root_block_device {
    volume_size = var.root_volume_size
    volume_type = "gp3"
  }

  tags = {
    Name = local.worker_names[count.index]
    Role = "worker"
  }
}

resource "aws_instance" "master" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.master_instance_type
  key_name               = aws_key_pair.cluster.key_name
  vpc_security_group_ids = [aws_security_group.k8s.id]

  root_block_device {
    volume_size = var.root_volume_size
    volume_type = "gp3"
  }

  tags = {
    Name = "master1"
    Role = "control-plane"
  }
}

# ---------------------------------------------------------------
# Bootstrap: install git, clone repo, run deploy.sh on master1
# ---------------------------------------------------------------

resource "terraform_data" "bootstrap" {
  count = var.run_deploy ? 1 : 0

  # Re-run if any instance is replaced
  triggers_replace = concat([aws_instance.master.id], aws_instance.workers[*].id)

  connection {
    type        = "ssh"
    host        = aws_instance.master.public_ip
    user        = "ubuntu"
    private_key = tls_private_key.cluster.private_key_openssh
    timeout     = "5m"
  }

  # Same key lets master1 reach the workers - no PEM pasting
  provisioner "file" {
    content     = tls_private_key.cluster.private_key_openssh
    destination = "/home/ubuntu/.ssh/k8s_cluster_key"
  }

  provisioner "remote-exec" {
    inline = [
      "set -e",
      "echo 'Waiting for cloud-init to finish (apt lock)...'",
      "cloud-init status --wait > /dev/null || true",
      "chmod 600 /home/ubuntu/.ssh/k8s_cluster_key",
      "sudo apt-get update -qq",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git",
      "rm -rf /home/ubuntu/k8-cluster-automation",
      "git clone --branch ${var.repo_branch} --depth 1 ${var.repo_url} /home/ubuntu/k8-cluster-automation",
      "chmod +x /home/ubuntu/k8-cluster-automation/deploy.sh",
      join(" ", [
        "MASTER_IP=${aws_instance.master.private_ip}",
        "CLIENT1_IP=${aws_instance.workers[0].private_ip}",
        "CLIENT2_IP=${aws_instance.workers[1].private_ip}",
        "CLUSTER_KEY=/home/ubuntu/.ssh/k8s_cluster_key",
        "/home/ubuntu/k8-cluster-automation/deploy.sh",
      ]),
    ]
  }
}
