---
- name: Initialize Kubernetes control plane
  ansible.builtin.command:
    cmd: kubeadm init --apiserver-advertise-address={{ hostvars['master1']['ansible_host'] }} --pod-network-cidr=10.244.0.0/16
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0700'

- name: Copy Kubernetes admin configuration
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0600'
